import '../css/homePage.css'

function HomePage() {
    return (
        <>
         <img className="HomePageImg" src="../../src/assets/astronaut-floating-space.png" alt="image generated by Dall e " />
        <div className='homePageContainer'>
            
        <h1>Educai</h1>
        <h2>Ya no es solo tu inteligencia</h2>
        </div>
          
        </>
    )
  }
  
  export {HomePage}